src/CurrencyApp.Web/Models/Calendar/DataCalendarViewModel.cs
using CurrencyApp.Web.Models.Dashboard;

namespace CurrencyApp.Web.Models.Calendar
{
    public class DataCalendarViewModel
    {
        public string? Base { get; set; }

        public string? Date { get; set; }

        public Dictionary<string, decimal> Rates { set; get; }
    }
}

src/CurrencyApp.Web/Models/Converter/ConverterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CurrencyApp.Web.Models.Converter
{
    public class ConverterViewModel
    {
        public ConverterViewModel()
        {
            this.Amount = 1;
            this.Date = DateTime.Now;
            this.Result = new List<ResultConverViewModel>();
        }
        public string? CurrencyPrincipal { get; set; }

        [Required(ErrorMessage = "Es necesario ingresar un monto.")]
        [Range(1,10000,ErrorMessage = "El monto ingresado no se encuentra dentro del rango valido.")]
        public decimal? Amount { get; set; }

        [Required(ErrorMessage ="Es necesario ingresar una fecha.")]
        public DateTime? Date { get; set; }

        public List<ResultConverViewModel> Result { get; set; }
    }

    public class ResultConverViewModel
    {
        public string? Name { get; set; }

        public decimal Amount { get; set; }
    }

}

src/CurrencyApp.Web/Models/Dashboard/DashboardViewModel.cs
namespace CurrencyApp.Web.Models.Dashboard
{
    public class DashboardViewModel
    {
        public decimal Amount { get; set; }

        public string? Base { get; set; }

        public string? Date { get; set; }

        public IEnumerable<RateViewModel>? Rates { get; set; }
    }

    public class RateViewModel
    {
        public decimal Amount { get; set; }
        public string? Base { get; set; }
    }
}

src/CurrencyApp.Web/Models/Management/ManagementViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CurrencyApp.Web.Models.Management
{
    public class ManagementViewModel
    {
        public string? SelectedCurrencyPrincipal { get; set; }

        public string? SelectedCurrencyFavorite { get; set; }

        public string? SelectedCurrenciesDelete { get; set; }

        public List<SelectListItem>? CurrenciesPrincipal { get; set; } = new();

        public List<SelectListItem>? CurrenciesFavorite { get; set; } = new();

        public IEnumerable<CurrencyViewModel>? CurrenciesFavorites { get; set; }

    }

    public class CurrencyViewModel
    {
        public string? Base { get; set; }

        public string? Name { get; set; }
    }

}

src/CurrencyApp.Web/Controllers/CalendarController.cs
using CurrencyApp.Application.IServices;
using CurrencyApp.Domain.Entities;
using CurrencyApp.Web.Filters;
using CurrencyApp.Web.Models.Calendar;
using Microsoft.AspNetCore.Mvc;

namespace CurrencyApp.Web.Controllers
{
    [RequestFilter]
    public class CalendarController : Controller
    {
        public readonly ICurrencyService _currencyService;

        public CalendarController(ICurrencyService currencyService)
        {
            _currencyService = currencyService;
        }
        [HttpGet("calendar")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost("calendar/historial")]
        public async Task<IActionResult> GetHistorial([FromBody] string date)
        {
            DataCalendarViewModel data = new DataCalendarViewModel();
            CurrencyRates? dataCalendar = await _currencyService.GetDataApi(date: DateTime.Parse(date));

            if (dataCalendar is not null)
            {
                data.Date = date;
                data.Rates = dataCalendar.Rates;
                data.Base = dataCalendar.Base;
            }

            return PartialView("_DataCalendar", data);
        }

    }
}

src/CurrencyApp.Web/Controllers/DashboardController.cs
using CurrencyApp.Application.IServices;
using CurrencyApp.Domain.Entities;
using CurrencyApp.Web.Filters;
using CurrencyApp.Web.Models.Dashboard;
using Microsoft.AspNetCore.Mvc;

namespace CurrencyApp.Web.Controllers;
public class DashboardController : Controller
{
    public readonly ICurrencyService _currencyService;

    public DashboardController(ICurrencyService currencyService)
    {
        _currencyService = currencyService;
    }

    [RequestFilter]
    [HttpGet("dashboard")]
    public async Task<IActionResult> Index()
    {
        DashboardViewModel dataResponse = new DashboardViewModel();
        CurrencyRates? dashboardResponse = await _currencyService.GetDataApi();

        if (dashboardResponse is not null)
        {
            dataResponse = new DashboardViewModel()
            {
                Amount = dashboardResponse.Amount,
                Base = dashboardResponse.Base,
                Date = dashboardResponse.Date,
                Rates = dashboardResponse.Rates.Select(data => new RateViewModel() { Amount = data.Value, Base = data.Key })
            };
        }

        return View(dataResponse);
    }
}

src/CurrencyApp.Web/Controllers/ManagementController.cs
using CurrencyApp.Application.IServices;
using CurrencyApp.Domain.Entities;
using CurrencyApp.Domain.Records;
using CurrencyApp.Web.Filters;
using CurrencyApp.Web.Helpers;
using CurrencyApp.Web.Models.Converter;
using CurrencyApp.Web.Models.Management;
using Microsoft.AspNetCore.Mvc;

namespace CurrencyApp.Web.Controllers;

[RequestFilter]
public class ManagementController : Controller
{
    private readonly ICurrencyService _currencyService;

    public ManagementController(ICurrencyService currencyService)
    {
        _currencyService = currencyService;
    }

    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> ChangeCurrency([FromForm] string selectedCurrencyPrincipal)
    {
        if (!string.IsNullOrEmpty(selectedCurrencyPrincipal))
        {
            string[] values = selectedCurrencyPrincipal.Split('-');
            await _currencyService.SaveCurrencyPrincipal(values[0], values[1]);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> ModifyCurrencyFavorite([FromForm] ManagementViewModel model, [FromForm] string action)
    {
        await _currencyService.ModifyCurrenciesFavorites(model.SelectedCurrencyFavorite, model.SelectedCurrenciesDelete, action);
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        ManagementViewModel managementViewModel = new();

        BuildDataManagement? buildDataManagement = await _currencyService.GetBuildDataManagement();

        if (buildDataManagement?.principalCurrency is not null)
            managementViewModel.SelectedCurrencyPrincipal = string.Concat(buildDataManagement.principalCurrency.Base,"-",buildDataManagement.principalCurrency.Description);

        managementViewModel.CurrenciesFavorites = buildDataManagement?.favoriteCurrency.Select(data =>
        {
            return new CurrencyViewModel { Base = data.Base, Name = data.Description };
        });

        managementViewModel.CurrenciesPrincipal?.AddRange(buildDataManagement.ItemsPrincipal.Map());
        managementViewModel.CurrenciesFavorite?.AddRange(buildDataManagement.ItemsFavorites.Map());

        return View(managementViewModel);
    }

    [HttpGet("converter")]
    public async Task<IActionResult> Converter()
    {
        ConverterViewModel converterViewModel = new();
        Currency? principalCurrency = await _currencyService.GetPrincipalCurrency();
        if (principalCurrency is null)
        {
            return View(converterViewModel);
        }
        converterViewModel.CurrencyPrincipal = string.Concat(principalCurrency.Base, "-", principalCurrency.Description);
        return View(converterViewModel);
    }

    [HttpPost]
    [AutoValidateAntiforgeryToken]
    public async Task<IActionResult> ConvertAmount([FromForm] ConverterViewModel model)
    {
        Currency? principalCurrency = await _currencyService.GetPrincipalCurrency();

        if (principalCurrency is null)
        {
            return View("Converter", new ConverterViewModel());
        }

        model.CurrencyPrincipal = string.Concat(principalCurrency.Base, "-", principalCurrency.Description);

        if (!ModelState.IsValid)
        {
            return View("Converter", model);
        }

        if (!string.IsNullOrEmpty(model.CurrencyPrincipal))
        {
            CurrencyRates? dashboard = await _currencyService.GetDataApi(model.Amount, model.Date);
            model.Result.AddRange(dashboard.Rates.Select(dt => new ResultConverViewModel() { Name = dt.Key, Amount = dt.Value }));
        }

        return View("Converter", model);
    }

}

src/CurrencyApp.Web/Views/Calendar/Index.cshtml
@{
    ViewData["Title"] = "Calendar";
}

<div class="container-principal calendar">
    <h1>Consultar historial de tasas</h1>
    <div id="calendar"></div>
    <div class="modal fade" id="modalData" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div id="modalBody" class="modal-body">
                </div>
                <div class="btn-group m-5 mb-2 mt-1">
                    <button type="button" class="m-3 mt-0 mb-0" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let calendarEl = document.getElementById('calendar');
                let today = new Date();
            let calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth',
                locale: 'es',
                selectable: true,
                validRange:{
                    end:today.toISOString()
                },
                buttonText: {
                    today: 'Hoy',
                    month: 'Mes',
                    week: 'Semana',
                    day: 'Día',
                    list: 'Lista'
                },dateClick: async function(info) {
                    let date = info.dateStr;
                    let res = await fetch("calendar/historial",
                    {
                        method:'POST',
                        body: JSON.stringify(date),
                        headers:{
                            "Content-Type":"application/json"
                        }
                    });

                    let modalEl = document.getElementById('modalData');
                    document.getElementById('modalBody').innerHTML = await res.text();
                    let dateModal = new bootstrap.Modal(modalEl);
                    dateModal.show();
                }
            });

            calendar.render();
        });
    </script>
}

src/CurrencyApp.Web/Views/Dashboard/Index.cshtml
@{
    ViewData["Title"] = "Dashboard Page";
}

@model DashboardViewModel

<div class="container-principal dashboard">
   
    <h1>Divisa principal</h1>

    <div class="dashboard-item">
        <p>Divisa principal: <strong>@(string.IsNullOrEmpty(Model.Base) ? "Es necesario seleccionar una divisa principal." : Model.Base)</strong></p>
        <p>Conversión: <strong>@Model.Amount</strong></p>
        <p>Fecha: <strong>@Model.Date</strong></p>
    </div>

    <h1>Divisa(s) favorita(s)</h1>

    <div class="dashboard-items">
        @if(Model.Rates is not null)
        { 
            @foreach (var rate in Model.Rates)
            {
                <div class="dashboard-item-rates">
                    <p>Divisa: <strong>@rate.Base</strong></p>
                    <p>Conversión: <strong>@rate.Amount</strong></p>
                </div>
            }        
        }
    </div>
</div>

src/CurrencyApp.Web/Views/Management/Converter.cshtml
@{
    ViewData["Title"] = "Converter Page";
}

@model ConverterViewModel
<div class="container-principal">

    <h1>Conversor de divisas</h1>
    <form asp-controller="Management" asp-action="ConvertAmount" method="post">
        <section class="section">
            <p>Divisa principal: <strong>@(Model.CurrencyPrincipal is null ? "Es necesario seleccionar una divisa principal." : Model.CurrencyPrincipal)</strong></p>
            @if (!string.IsNullOrEmpty(Model.CurrencyPrincipal))
            {
                <h3>Monto</h3>
                <input asp-for="Amount" class="inputForm" type="number" />
                <span class="text-danger" asp-validation-for="Amount"></span>
                <h3>Fecha</h3>
                <input max="@Model.Date.Value.ToString("yyyy-MM-dd")" asp-for="Date" class="inputForm" type="date" />
                <span class="text-danger" asp-validation-for="Date"></span>
                <div class="btn-group">
                    <button>Convertir</button>
                </div>
            }
        </section>
    </form>
    @if (Model.Result is not null && Model.Result.Any())
    {
        <div class="dashboard-items">
            @foreach (var rate in Model.Result)
            {
                <div class="dashboard-item-rates">
                    <p>Divisa: <strong id="selectedMain">@rate.Name</strong></p>
                    <p>Conversión: <strong id="selectedMain">@rate.Amount</strong></p>
                </div>
            }
        </div>
    }
</div>

src/CurrencyApp.Web/Views/Management/Index.cshtml
@{
    ViewData["Title"] = "Management Page";
}

@model ManagementViewModel

<div class="container-principal">
    <h1>Gestión de divisas</h1>

    <form asp-controller="Management" asp-action="ChangeCurrency" method="post">
        <section class="section">
            <h3>Divisa principal</h3>
            <select asp-for="SelectedCurrencyPrincipal" asp-items="@Model.CurrenciesPrincipal"></select>
            @if (!string.IsNullOrEmpty(Model.SelectedCurrencyPrincipal))
            {
                <p>Divisa principal: <strong id="selectedMain">@Model.SelectedCurrencyPrincipal</strong></p>
            }
            <div class="btn-group">
                <button>Seleccionar</button>
            </div>
        </section>
    </form>
    <form asp-controller="Management" asp-action="ModifyCurrencyFavorite" method="post">
        <section class="section">
            <h3>Divisa(s) favorita(s)</h3>
            <select asp-for="SelectedCurrencyFavorite" asp-items="@Model.CurrenciesFavorite"></select>
            <div class="btn-group">
                <button name="action" value="add">+ Agregar</button>
                <button name="action" value="remove">- Remover</button>
            </div>
            <ul id="favorites" class="favorites">
                @if (Model.CurrenciesFavorites != null)
                {
                    foreach (var currency in Model.CurrenciesFavorites)
                    {
                        <li><input asp-for="SelectedCurrenciesDelete" value="@currency.Base" type="radio" /> @currency.Base - @currency.Name</li>
                    }
                }
            </ul>
        </section>
    </form>

</div>

src/CurrencyApp.Web/Views/Shared/_DataCalendar.cshtml
@{
    Layout = null;
}

@model DataCalendarViewModel


<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

<div class="container-principal dashboard mb-1 mt-1">

    <h1>Divisa principal</h1>

    <div class="dashboard-item">
        <p>Divisa principal: <strong>@(string.IsNullOrEmpty(Model.Base) ? "Es necesario seleccionar una divisa principal." : Model.Base)</strong></p>
        <p>Fecha: <strong>@Model.Date</strong></p>
    </div>

    <h1>Divisa(s) favorita(s)</h1>

    <div class="dashboard-items">
        @if (Model.Rates is not null)
        {
            @foreach (var rate in Model.Rates)
            {
                <div class="dashboard-item-rates">
                    <p>Divisa: <strong>@rate.Key</strong></p>
                    <p>Conversión: <strong>@rate.Value</strong></p>
                </div>
            }
        }
    </div>
</div>

src/CurrencyApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CurrencyApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CurrencyApp.Web.styles.css" asp-append-version="true" />    
    <script src="~/lib/fullcalendar/index.global.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Management" asp-action="Index">CurrencyApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Management" asp-action="Index">Gestión</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calendar" asp-action="Index">Historial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Management" asp-action="Converter">Conversor</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>